#+TITLE: Completion
#+STARTUP: OVERVIEW
* Introduction
For configuring autocompleting options. We begin with the a built-in
hippie-expand by binding it

#+BEGIN_SRC emacs-lisp
  (general-define-key
   "C-c h" 'hippie-expand)
#+END_SRC

* Corfu
General autocompletion system, but mostly used in programming
contexts. We complete text with `TAB` across Emacs' buffers.
#+BEGIN_SRC emacs-lisp
  (use-package corfu
    :init
    (global-corfu-mode)
    :config
    (setq corfu-cycle t
          corfu-quit-at-boundary nil
          corfu-quit-no-match nil
          corfu-preview-current t
          corfu-preselect 'first
          corfu-scroll-margin 5))

  (setq completion-cycle-threshold 3)

  ;; Emacs 28: Hide commands in M-x which do not apply to the current mode.
  ;; Corfu commands are hidden, since they are not supposed to be used via M-x.
  (setq read-extended-command-predicate
        #'command-completion-default-include-p)

  ;; Enable indentation+completion using the TAB key.
  ;; `completion-at-point' is often bound to M-TAB.
  (setq tab-always-indent 'complete)
#+END_SRC

* Orderless
Provides completion styles to be used on top-of a completion packages
such as `Vertico` or certain `Consult` functions. If we do `C-x C-f`
and have two files `languages-and-modes.org` and `general.org` then
the search string `g l` will match both if we have set `'orderless`
style (ie. the order of your serach words does not matter).
#+BEGIN_SRC emacs-lisp
  (use-package orderless
    :custom
    (completion-styles '(orderless))
    (completion-category-overrides '((file (styles partial-completion)))))
#+END_SRC

* Vertico
Minibuffer completion system. It will display a vertical scrolling
minibuffer in modes like `M-x` or `(find-file)`.
#+BEGIN_SRC emacs-lisp
  (use-package vertico
    :init
    (vertico-mode)
    :config
    ;; Use `consult-completion-in-region' if Vertico is enabled.
    ;; Otherwise use the default `completion--in-region' function.
    (setq completion-in-region-function
          (lambda (&rest args)
            (apply (if vertico-mode
                       #'consult-completion-in-region
                     #'completion--in-region)
                   args))))
#+END_SRC

* YASnippet
Enables snippets for progamming and text modes. Disable it for `TAB`
which we use for completion at point.
#+BEGIN_SRC emacs-lisp
  (use-package yasnippet
    :config
    (yas-reload-all)
    :bind (:map yas-minor-mode-map
                ("C-c y" . yas-expand)
                ("TAB" . nil)
                ("<tab>" . nil))
    :hook ((prog-mode text-mode) . yas-minor-mode))

  (use-package yasnippet-snippets
    :after yasnippet)
#+END_SRC
