#+TITLE: General Settings
#+STARTUP: OVERVIEW
* Autosave and Backups
Saves all backups to user's Emacs directory and in addition creates
numbered backups. First things first, we create autosave and backup
directory where we put autosaves and backups respectevily.
#+BEGIN_SRC emacs-lisp
  (defcustom hesam-autosave-directory (expand-file-name "autosave/" user-emacs-directory)
    "Directory where autosave and backups are put."
    :type 'directory
    :group 'hesam)

  (defcustom hesam-backup-directory (expand-file-name "backup/" user-emacs-directory)
    "Directory where autosave and backups are put."
    :type 'directory
    :group 'hesam)
#+END_SRC

Of course we need to make sure these directories exists
#+BEGIN_SRC emacs-lisp
  (dolist (dir (list hesam-autosave-directory hesam-backup-directory))
    (unless (file-directory-p dir)
      (make-directory dir)))
#+END_SRC

Use the directory for backups. There are some other sane settings used
described below with comments.
#+BEGIN_SRC emacs-lisp
  (setq backup-directory-alist `(("." . ,hesam-backup-directory))
	version-control t		  ; Use version numbers for backups.
	vc-make-backup-files t	  ; Make backups for git files
	kept-new-versions 1000	  ; Number of newest versions to keep.
	kept-old-versions 0	  ; Number of oldest versions to keep.
	delete-old-versions t ; Don't ask to delete excess backup versions.
	backup-by-copying t)  ; Copy all files, don't rename them.
#+END_SRC

But backups are only created once when the buffer is visited. We want
to save backups on each save. We do so by resetting the flag that
tells Emacs that the file has been backed up. Adding a hook to do that
after each save will make Emacs backup the file since the counter has
been reset.
#+BEGIN_SRC emacs-lisp
  (defun force-backup-of-buffer ()
    (setq buffer-backed-up nil))
  (add-hook 'before-save-hook  'force-backup-of-buffer)
#+END_SRC

We also make sure to organize our autosaves in user's Emacs directory.
#+BEGIN_SRC emacs-lisp
  (setq auto-save-file-name-transforms
	`((".*" ,hesam-autosave-directory t)))
#+END_SRC

* Bookmarks
Saving bookmarks to Dropbox and auto-saving upon change.
#+BEGIN_SRC emacs-lisp
  (setq bookmark-default-file "~/Dropbox/emacs/bookmarks"
        ;; num changes before saving bookmark
        bookmark-save-flag 1)
#+END_SRC

* Calendar and Time
Configuration for calendar, setting ISO formats and start of week.
#+BEGIN_SRC emacs-lisp
  ;; start with Mon
  (setq calendar-week-start-day 1)

  ;; EU style
  (setq calendar-date-style 'european)

  ;; Date format
  (setq calendar-date-display-form
        '((if dayname
              (concat dayname ", "))
          day " " monthname " " year))

  ;; 24-clock
  (setq calendar-time-display-form
        '(24-hours ":" minutes))

  ;; show week numbers
  (setq calendar-intermonth-text
        '(propertize
          (format "W%2d"
                  (car
                   (calendar-iso-from-absolute
                    (calendar-absolute-from-gregorian (list month day year)))))
          'font-lock-face 'calendar-iso-week-face))
#+END_SRC

And if we ever need it the display is on 24h format, we don't display
load-average
#+BEGIN_SRC emacs-lisp
  (setq display-time-24hr-format t
        display-time-day-and-date nil
        display-time-default-load-average nil)
#+END_SRC

* Disable suspend functions
We don't want to ever suspend Emacs or the frame. Therefore display a
warning when these commands are run.
#+BEGIN_SRC emacs-lisp
  (put 'suspend-frame 'disabled t)
  (put 'suspend-emacs 'disabled t)
#+END_SRC

* Inhibiting Bells and Warnings
Finding it too annoying hearing beeping sounds and seeing visual we
alamrs we turn all of them completely off.
#+BEGIN_SRC emacs-lisp
  ;; no beeping
  (setq ring-bell-function 'ignore)
#+END_SRC

Inhibits native compilation warnings which happens intermittently.
#+BEGIN_SRC emacs-lisp
  ;; to avoid getting spammed with warnings
  (setq native-comp-async-report-warnings-errors 'silent)
#+END_SRC

* Loading untracked settings
Helper function `hesam/load-if-exists` to load any files if they
exist. These are not meant to be tracked by git. We also set the
custom-file variable to notifty emacs customization options not
tracked by git shall be saved there, instead of default in the init
file.
#+BEGIN_SRC emacs-lisp
  (defun hesam/load-if-exists (path)
    (if (file-exists-p path)
        (load path)))

  (setq custom-file "~/.emacs.d/emacs-custom.el")
  (hesam/load-if-exists custom-file)
  (hesam/load-if-exists "~/.emacs.d/macros.el")
  (hesam/load-if-exists "~/.emacs.d/local.el")
#+END_SRC

* Openwith
A package that helps with opening files in an external app, such as
opening `.doc` files in `libreoffice`.
#+BEGIN_SRC emacs-lisp
  (use-package openwith
    :config
    (setq openwith-associations
          (list
           (list (openwith-make-extension-regexp
                  '("mpg" "mpeg" "mp3" "mp4"
                    "avi" "wmv" "wav" "mov" "flv"
                    "ogm" "ogg" "mkv" "rar"))
                 "mpv --no-border"
                 '(file))
           (list (openwith-make-extension-regexp
                  '("doc" "xls" "ppt" "odt" "ods" "odg" "odp"))
                 "libreoffice"
                 '(file))))
    (openwith-mode 1))
#+END_SRC

* Repeat mode
Allows us to repeat commands. For example, to use the next tab command
we do "C-x t o" twice. But with repeat mode it suffices to do "C-x t
o" once and followed by arbitrarily many "o".
#+BEGIN_SRC emacs-lisp
  (repeat-mode t)
#+END_SRC

* Reverting
Will automatically load changed buffers, this can for example happen
if we use git to reset recent changes.
#+BEGIN_SRC emacs-lisp
  (global-auto-revert-mode t)
#+END_SRC

And make use of the quick revert setting when reverting files with
`C-x x g`
#+BEGIN_SRC emacs-lisp
  (setq revert-buffer-quick-short-answers t)
#+END_SRC

* Savehist mode
Save minibuffer commands in a file that is loaded at startup
#+BEGIN_SRC emacs-lisp
  (savehist-mode t)
#+END_SRC

* Server
Starts emacs server at startup so that emacsclient can connect to
it. This preferably used in conjunction with systemd --user to
initialize emacs after login.
#+BEGIN_SRC emacs-lisp
  (require 'server)
  (unless (server-running-p)
    (server-start))
#+END_SRC

When we connect to the server Emacs will display about how to exit
with `C-x 5 0`. As we are already familiar with this command we
inhibit it.
#+BEGIN_SRC emacs-lisp
  (setq server-client-instructions nil)
#+END_SRC

* Subword
Allows for moving over a word based on the subwords in the table
below. From the manual we have a table to show us the meaning of this
minor mode.

  Nomenclature           Subwords
  ===========================================================
  GtkWindow          =>  "Gtk" and "Window"
  EmacsFrameClass    =>  "Emacs", "Frame" and "Class"
  NSGraphicsContext  =>  "NS", "Graphics" and "Context"
#+BEGIN_SRC emacs-lisp
  (global-subword-mode 1)
#+END_SRC

* Narrow
Allow narrowing `C-x n n` to a region. It makes sense to have it off
and warn the user by default. But once you familiarize with the mode
it's okay to allow it. Simply put, this command lets you only display
the region you selected.
#+BEGIN_SRC emacs-lisp
  (put 'narrow-to-region 'disabled nil)
#+END_SRC
