* Introduction
In this file we define global variables to be consumed in other
files. For example, the `leader-meta-spc` is global leader key used in
many places and theming variables for colors too.

* The package `general`
Simplifies setting keybindings and has advanced features for
prefix/leader keys.
#+BEGIN_SRC emacs-lisp
  (use-package general
    :init
    (general-auto-unbind-keys))
#+END_SRC

* Leaders Keys
Here we define leaders to be used throughout emacs. We have other
leader-keys that could be defined elsewhere because they are related
to a specifc file. For example as `leader-agenda-gtd` could be placed
in `org-mode.org`. But we prefer to put them here to have all leaders
in one place.


#+BEGIN_SRC emacs-lisp
  ;; Prefix to be used for all kinds of stuff
  (general-create-definer leader-meta-spc
    :prefix "M-SPC")

  ;; Sub-leader for agenda & GTD
  (general-create-definer leader-org-mode
    :prefix "C-c o")

  ;; Sub-leader for redshift
  (general-create-definer leader-super-r
    :prefix "M-SPC r")

  ;; Leader for editing text
  (general-create-definer leader-editing
    :prefix "C-c e")

  ;; Leader for window management
  (general-create-definer leader-window
    :prefix "C-c w")
#+END_SRC

* Theme
Use the Dracula theme for Emacs and define the palette here so we can
use its values in our configuration elsewhere.
#+BEGIN_SRC emacs-lisp
  (use-package dracula-theme
    :config
    (load-theme 'dracula t)
    (setq dracula-enlarge-headings nil)
    ;; We don't like the match face provided by Dracula so we change it
    ;; here -- as this should only be done if this theme is used.
    (set-face-attribute 'match nil :background "#bd93f9"))
#+END_SRC

Throught our configuration we will supply an easy way of getting the
colors. Note that if we change theme then most-likely we need to
change the `hesam/theme-colrs-alist` as well. In this aspect it's a
bit of a flaw because we cannot easily switch themes.
#+BEGIN_SRC emacs-lisp
  (defun hesam/theme-color (color)
    "Retrieve the color code for COLOR from `hesam/theme-colors-alist'."
    (cdr (assoc color hesam/theme-colors-alist)))

  (defvar hesam/theme-colors-alist
    ;; Dracula palette
    '((bg      . "#282a36")
      (fg      . "#f8f8f2")
      (current . "#44475a")
      (comment . "#6272a4")
      (cyan    . "#8be9fd")
      (green   . "#50fa7b")
      (orange  . "#ffb86c")
      (pink    . "#ff79c6")
      (purple  . "#bd93f9")
      (red     . "#ff5555")
      (yellow  . "#f1fa8c")
      (white   . "#f8f8f2")))
#+END_SRC
