* Introduction
This is not an exhaustive list of all packages used in our
configuration. Rather we have put packages here that we couldn't
motivate putting elsewhere under our directory tree.

For example, in `programming.org` we have declared `magit`
package. But it makes sense to have it there since it has a clear
connection with programming. Another package `general` is declared in
`bindings.org` since it's used to for defining keybindings easily.

* expand region
Will expand mark in regions that makes sense, ie. is context aware.
#+BEGIN_SRC emacs-lisp
  (use-package expand-region
    :bind ("C-c =" . 'er/expand-region))
#+END_SRC

* pdf-tools
A major mode for viewing PDF files inside Emacs. Ordinary `'isearch`
works best in PDF tools which is why we explicitly set it for
`PDFView` mode.
#+BEGIN_SRC emacs-lisp
  (use-package pdf-tools
    :config (pdf-tools-install)
    :bind-keymap
    ("C-s" . isearch-forward)
    ("C-r" . isearch-backward))
#+END_SRC

** auxtex
TeX should be open with PDF tools.
#+BEGIN_SRC emacs-lisp
  (setq TeX-view-program-selection '((output-pdf "PDF Tools"))
        TeX-source-correlate-start-server t)

  ;; Update PDF buffers after successful LaTeX runs
  (add-hook 'TeX-after-compilation-finished-functions
            #'TeX-revert-document-buffer)
#+END_SRC

** midnight mode
#+BEGIN_SRC emacs-lisp
  ;;; set colors for pdf-tools, the var expects cons
  ;; (setq pdf-view-midnight-colors (cons (doom-color 'fg) (doom-color 'bg)))
  (setq pdf-view-midnight-colors (cons "#ffffff" "#000000"))
#+END_SRC
