#+TITLE: Org mode settings
#+STARTUP: overview
* Package Declaration
Sets up org mode and defines several useful settings. Prettifies
buffer as well.
#+BEGIN_SRC emacs-lisp
  (use-package org
    :init
    (setq org-src-window-setup 'current-window
          org-directory "~/Dropbox/org"))
#+END_SRC

* Babel
What lanaguages to support for literal programming in Org buffers.
#+BEGIN_SRC emacs-lisp
  (org-babel-do-load-languages
   'org-babel-load-languages
   '((C . t)
     (python . t)
     (shell . t)))
#+END_SRC

* Agenda and GTD
Agenda files are stored in Dropbox under `org/agenda`. If we put our
GTD file inside `org-agenda-files`, then any dates in the GTD file
will be seen by org agenda. We also define some nice tags to use so
that we can filter on them in the Agenda view.
#+BEGIN_SRC emacs-lisp
    (setq gtd-file (concat (eval org-directory) "/agenda/gtd.org"))
    (setq org-agenda-files `(,gtd-file)
          org-default-notes-file "~/Dropbox/org/notes.org"
          org-tag-alist '(("@work" . ?w) ("@home" . ?h)))
#+END_SRC

`org-outline-path-complete-in-steps` when set to nil allows selection
of the refile target using a single completion step, which will
provide a faster selection method if you have deeply nested
structures.
#+BEGIN_SRC emacs-lisp
  (setq org-outline-path-complete-in-steps t)
#+END_SRC

When refiling target is GTD file we want to automatically save the
buffer.
#+BEGIN_SRC emacs-lisp
  (defun hesam/org-refile-save (&rest _)
    "Save the buffer after refiling.

     This function checks if the current buffer is visiting 'gtd.org'.
     If so, it saves the buffer. It is used as an advice to `org-refile`,
     meaning it is called every time after `org-refile` is invoked."
    (when (eq (current-buffer) (find-buffer-visiting "gtd.org"))
      (save-buffer)))

  (advice-add 'org-refile :after 'hesam/org-refile-save)
#+END_SRC

Defines a toggler to show our GTD file whenever it is not visible in
the window and to hide it if it is.
#+BEGIN_SRC emacs-lisp
  (defun gtd/toggle-doing ()
    "Access the GTD gtd.org file inside `gtd-directory'.
    The tasks in this file are actively working on. If the buffer
    is visible then delete it, else open it in another window."
    (interactive)
    (let ((buf (get-buffer "gtd.org")))
      (if (and buf (get-buffer-window buf))
          (delete-window (get-buffer-window buf))
        (find-file-other-window gtd-file))))
#+END_SRC

** View
Start with current day and do not show tasks that are done.
#+BEGIN_SRC emacs-lisp
  (setq org-agenda-start-on-weekday nil
        org-agenda-skip-deadline-if-done t
        org-agenda-skip-scheduled-if-done t
        org-agenda-show-all-dates t)
#+END_SRC

From emacs cafe [[https://emacs.cafe/emacs/orgmode/gtd/2017/06/30/orgmode-gtd.html][blog]] to get gtd context filtered in the dispatcher.
#+BEGIN_SRC emacs-lisp
  (setq org-agenda-custom-commands
        '(("w" "Context work" tags-todo "@work"
           ((org-agenda-overriding-header "Work")
            (org-agenda-skip-function #'my-org-agenda-skip-all-siblings-but-first)))
          ("h" "Context home" tags-todo "@home"
           ((org-agenda-overriding-header "Home")
            (org-agenda-skip-function #'my-org-agenda-skip-all-siblings-but-first)))))

  (defun my-org-agenda-skip-all-siblings-but-first ()
    "Skip all but the first non-done entry."
    (let (should-skip-entry)
      (unless (org-current-is-todo)
        (setq should-skip-entry t))
      (save-excursion
        (while (and (not should-skip-entry) (org-goto-sibling t))
          (when (org-current-is-todo)
            (setq should-skip-entry t))))
      (when should-skip-entry
        (or (outline-next-heading)
            (goto-char (point-max))))))

  (defun org-current-is-todo ()
    (string= "TODO" (org-get-todo-state)))
#+END_SRC

** Keybindings
For accessing Org agenda and GTD quickly.
#+BEGIN_SRC emacs-lisp
(leader-org-mode
    "a" 'org-agenda
    "c" 'org-capture
    "g" 'gtd/toggle-doing
    "l" 'org-store-link
    "i" 'gtd/inbox
    "s" 'gtd/someday
    "t" 'gtd/tickler
    "x" 'org-archive-subtree)

  (leader-org-mode
    :keymaps 'org-mode-map
    "r" 'org-refile)
#+END_SRC

** Templates
Storage for Org capture is set to Dropbox to provide syncing between
devices.
#+BEGIN_SRC emacs-lisp
  (setq org-capture-templates
        '(("i" "Inbox" entry
           (file+headline gtd-file "Inbox") "* %U %i%?")
          ("p" "Planned" entry
           (file+headline gtd-file "Planned") "* %T %i%?")))
#+END_SRC

* Appearance
Settings that related to how Org buffers are displayed.
** Org bullets
These are prettier bullet points next to headers.
#+BEGIN_SRC emacs-lisp
  (use-package org-bullets
  :config
  (add-hook 'org-mode-hook (lambda () (org-bullets-mode 1))))
#+END_SRC

** Misc
#+BEGIN_SRC emacs-lisp
  (setq org-startup-indented t
        org-hide-emphasis-markers t
        org-agenda-block-separator ""
        org-fontify-whole-heading-line t
        org-fontify-done-headline t
        org-fontify-quote-and-verse-blocks t)
#+END_SRC

** Prettify
Prettifies symbols recongized by Org mode, such as [X] in TODO lists.
#+BEGIN_SRC emacs-lisp
  (add-hook 'org-mode-hook (lambda ()
     "Beautify Org Checkbox Symbol"
     (push '("[X]" . "✓") prettify-symbols-alist)
     (push '("[ ]" . "□") prettify-symbols-alist)
     (prettify-symbols-mode)))
#+END_SRC

