#+TITLE: Progamming Settings
#+STARTUP: OVERVIEW
* Introduction
Programming related settings and packages defined here. Language
Server Protocol (LSP) provides IDE-like features and is configured
here. Some relevant minor modes also set here, including their look
and feel if appropriate. But first... let's get rid of tabs!
#+BEGIN_SRC emacs-lisp
  (setq-default indent-tabs-mode nil)
#+END_SRC

* Programming Languages Modes
** Rust
Rust-specific settings and packages. First install the major mode
#+BEGIN_SRC emacs-lisp
  (use-package rust-mode)
#+END_SRC

Now install `rustic` package which provides a rich Rust development
environment.
#+BEGIN_SRC emacs-lisp
  (use-package rustic
    :config
    (setq rustic-format-on-save nil
	  rustic-lsp-client 'eglot
	  rustic-ansi-faces (vector
			     "black"
			     (hesam/theme-color 'red)
			     (hesam/theme-color 'green)
			     (hesam/theme-color 'yellow)
			     (hesam/theme-color 'purple)
			     (hesam/theme-color 'pink)
			     (hesam/theme-color 'cyan)
			     (hesam/theme-color 'white))))
  #+END_SRC

** Python
Python-specific settings and packages.
*** auto-virtualenv
Automatically activate Python virtual environments with `auto-virtualenv`.
#+BEGIN_SRC emacs-lisp
  (use-package auto-virtualenv
    :demand t
    :after project
    :config
    (advice-add #'project-switch-to-buffer :after #'auto-virtualenv-set-virtualenv)
    :hook (python-mode . auto-virtualenv-set-virtualenv))
#+END_SRC

*** black
#+BEGIN_SRC emacs-lisp
  (use-package python-black
    :demand t
    :after python
    :hook (python-mode . python-black-on-save-mode-enable-dwim))
#+END_SRC

*** pyenv
Use `pyvenv` to manage Python virtual environments.
#+BEGIN_SRC emacs-lisp
  (use-package pyvenv)
#+END_SRC

* Language Server Protocol
Setup Language Server Protocol (LSP) for different programming
languages. We use eglot which is built-in >= Emacs 29.
#+BEGIN_SRC emacs-lisp
  (use-package eglot
    :after project
    :defer t
    :bind (:map eglot-mode-map
                ("C-c e r" . eglot-rename)
                ("C-c e f" . eglot-format)
                ("C-c e d" . eglot-find-declaration)
                ("C-c e i" . eglot-find-implementation))
    :config
    (set-face-attribute 'eglot-highlight-symbol-face nil
                        :inherit 'match)
    :hook ((rust-mode python-mode) . eglot-ensure))

  (use-package eldoc-box
    :after eglot
    :defer t
    :config
    (set-face-attribute 'eldoc-box-body nil
                        :inherit 'default))
#+END_SRC

* Modes
Many of these mode are activated by adding a hook to `prog-mode-hook`
or is highly associated with programming.
** ediff
Ediff is used for viewing diffs and acting upon them. We want the
control that normally displays in another frame to be place in the
same window.
#+BEGIN_SRC emacs-lisp
  (setq ediff-window-setup-function 'ediff-setup-windows-plain)
#+END_SRC

** electric mode
Automatically add closing brackets and indent code in `prog-mode`.
#+BEGIN_SRC emacs-lisp
  (defun hesam/electric ()
    (electric-pair-local-mode t)
    (electric-indent-local-mode t))
  (add-hook 'prog-mode-hook #'hesam/electric)
#+END_SRC

** hideshow
Set up the `hideshow` minor mode for `prog-mode`.
#+BEGIN_SRC emacs-lisp
  (setq hs-allow-nesting t)
  (add-hook 'prog-mode-hook 'hs-minor-mode)
  (eval-after-load 'prog-mode
    '(define-key prog-mode-map (kbd "C-<return>") 'hs-toggle-hiding))
#+END_SRC

Another symbol to be used for collapsed text.
#+BEGIN_SRC emacs-lisp
  (set-display-table-slot standard-display-table
                          'selective-display (string-to-vector " [+] "))
#+END_SRC

** row/column/line numbers
Shows column number in `mode-line` in addtion to row number.
#+BEGIN_SRC emacs-lisp
  (add-hook 'prog-mode-hook 'column-number-mode)
#+END_SRC

** Show parent
Highlights matching parens in prog-mode.
#+BEGIN_SRC emacs-lisp
  (add-hook 'prog-mode-hook 'show-paren-mode)
#+END_SRC

* git
** git-timemachine
In a git-tracked repository we can invoke `git-timemachine` to quickly
navigate between revisions, show commits and use git blame. When
visiting a git tracked file and calling `git-timemachine`
interatively, it allows us to move between revisions with `n`,
`p`. Hit `?` to get a hydra-like menu for more commands.
#+BEGIN_SRC emacs-lisp
  (use-package git-timemachine
    :after magit)
#+END_SRC

** Magit
git porcelain
#+BEGIN_SRC emacs-lisp
  (use-package magit
    :demand t
    :after project
    :bind ("C-c g" . magit-status)
    :config
    (advice-add #'project-vc-dir :override #'magit-project-status))
#+END_SRC

* Flymake
Flymake is an built-in syntax checker for Emacs to be used everywhere,
but it's stronlgy linked to programming and that is why we define it
here.

Out of intereset here is the setting `flymake-no-changes-timeout`. If
set to a number, then Flymake will check the file after waiting that
number in seconds for each change you make in the buffer.
#+BEGIN_SRC emacs-lisp
  (use-package flymake
    :config
    (setq flymake-fringe-indicator-position 'left-fringe
          flymake-suppress-zero-counters t
          flymake-start-on-flymake-mode t
          flymake-no-changes-timeout 0.5
          flymake-start-on-save-buffer t
          flymake-proc-compilation-prevents-syntax-check t
          flymake-wrap-around nil))
#+END_SRC

* Project
Project management tool using git to detect root. Prefix `C-x p` to
run project commands like visiting buffers and files associated with
the project. We can also start a terminal in the project root or VC.
#+BEGIN_SRC emacs-lisp
  (use-package project)
#+END_SRC

* Treemacs
A tree renderer of your directory. Useful for seeing files in your
project and includes integration with magit.
#+BEGIN_SRC emacs-lisp
  (use-package treemacs
    :defer t
    :config
    (setq treemacs-no-png-images t)
    ;; adjust root face as it's otherwise bold and bigger
    (set-face-attribute 'treemacs-root-face nil
                        :height 1.0
                        :underline nil
                        :inherit font-lock-constant-face)
    :bind (("C-c t b"   . treemacs-select-window)
           ("C-c t 1"   . treemacs-delete-other-windows)
           ("C-c t B"   . treemacs-bookmark)
           ("C-c t C-t" . treemacs-find-file)
           ("C-c t M-t" . treemacs-find-tag)
           ("C-c t d"   . treemacs-select-directory)
           ("C-c t t"   . treemacs)))

  (use-package treemacs-magit
    :after (treemacs magit))

  (use-package treemacs-tab-bar ;;treemacs-tab-bar if you use tab-bar-mode
    :after treemacs
    :config (treemacs-set-scope-type 'Tabs))
#+END_SRC

* vundo
In this excellet [[https://archive.casouri.cc/note/2021/visual-undo-tree/index.html][blog]] Yuan Fu describes a way of creating an undo-tree
from Emacs' linear tree. This enables us to build an undo-tree on the
fly, navigate it and make Emacs go to that state. Born is the package
`vundo` (visualize undo).
#+BEGIN_SRC emacs-lisp
  (use-package vundo)
#+END_SRC

* ws-butler
Removes trailing space and tabs from this user modified lines.
#+BEGIN_SRC emacs-lisp
  (use-package ws-butler
    :hook ((prog-mode text-mode) . ws-butler-mode))
#+END_SRC

