* Introduction
Programming related settings and packages defined here. Language
Server Protocol (LSP) provides IDE-like features and is configured
here. Some relevant minor modes also set here, including their look
and feel if appropriate.

* Programming Languages Modes
** C
Style settings for C-programming language.
#+BEGIN_SRC emacs-lisp
  (setq c-default-style '((java-mode . "java")
                          (awk-mode . "awk")
                          (other . "k&r")))
#+END_SRC

** Rust
Rust-specific settings and packages. First install the major mode
#+BEGIN_SRC emacs-lisp
  (use-package rust-mode)
#+END_SRC

Now install `rustic` package which provides a rich Rust development
environment.
#+BEGIN_SRC emacs-lisp
  (use-package rustic
    :init
    (setq rustic-ansi-faces (vector
                             "black"
                             dracula-red
                             dracula-green
                             dracula-yellow
                             dracula-purple
                             dracula-pink
                             dracula-cyan
                             dracula-white))
    :config
    (setq rustic-format-on-save t))
  #+END_SRC

** Python
Python-specific settings and packages.
*** auto-virtualenv
Automatically activate Python virtual environments with `auto-virtualenv`.
#+BEGIN_SRC emacs-lisp
  (use-package auto-virtualenv
    :hook (python-mode . auto-virtualenv-set-virtualenv))
#+END_SRC

*** black
#+BEGIN_SRC emacs-lisp
  (use-package python-black
    :demand t
    :after python
    :hook (python-mode . python-black-on-save-mode-enable-dwim))
#+END_SRC

*** pyenv
Use `pyvenv` to manage Python virtual environments.
#+BEGIN_SRC emacs-lisp
  (use-package pyvenv)
#+END_SRC

* Language Server Protocol
Setup Language Server Protocol (LSP) for different programming languages.
#+BEGIN_SRC emacs-lisp
  (use-package lsp-mode
    :init
    (setq lsp-keymap-prefix "C-c l")
    :config
    (setq lsp-headerline-breadcrumb-enable nil)
    :commands lsp
    :custom
    (lsp-idle-delay 0.25)

    ;; Rust
    (lsp-rust-analyzer-cargo-watch-command "check")
    (lsp-rust-analyzer-server-display-inlay-hints t)
    (lsp-rust-analyzer-display-chaining-hints t)
    (lsp-rust-analyzer-display-closure-return-type-hints t)

    :hook ((python-mode . lsp)
           (rust-mode . lsp)
           (lsp-mode . lsp-ui-mode)
           (lsp-mode . lsp-enable-which-key-integration)))
#+END_SRC

`lsp-ui` is an enhancement package that can show diagnostics and other
helpful information directly in the buffer.
#+BEGIN_SRC emacs-lisp
  (use-package lsp-ui
    :commands lsp-ui-mode
    :custom
    (lsp-ui-peek-always-show t)
    (lsp-ui-sideline-mode t)
    (lsp-ui-sideline-show-symbol nil))
  #+END_SRC

  Uses treemacs as tree renderer to show helpful LSP commands.
  #+BEGIN_SRC emacs-lisp
  (use-package lsp-treemacs
    :commands lsp-treemacs-errors-list)
  #+END_SRC

* Modes
** electric mode
Automatically add closing brackets and indent code in `prog-mode`.
#+BEGIN_SRC emacs-lisp
  (defun hesam/electric ()
    (electric-pair-local-mode t)
    (electric-indent-local-mode t))
  (add-hook 'prog-mode-hook #'hesam/electric)
#+END_SRC

** hideshow
Set up the `hideshow` minor mode for `prog-mode`.
#+BEGIN_SRC emacs-lisp
  (setq hs-allow-nesting t)
  (eval-after-load 'prog-mode
    '(define-key prog-mode-map (kbd "C-<return>") 'hs-toggle-hiding))
#+END_SRC

Another symbol to be used for collapsed text.
#+BEGIN_SRC emacs-lisp
  (set-display-table-slot standard-display-table
                          'selective-display (string-to-vector " [+] "))
#+END_SRC

** row/column/line numbers
Shows column number in `mode-line` in addtion to row number.
#+BEGIN_SRC emacs-lisp
  (add-hook 'prog-mode-hook 'column-number-mode)
#+END_SRC

** Show parent
Highlights matching parens in prog-mode.
#+BEGIN_SRC emacs-lisp
  (add-hook 'prog-mode-hook 'show-paren-mode)
#+END_SRC

* Flycheck
Flycheck is a modern syntax checker for Emacs to be used everywhere,
but it's stronlgy linked to programming and that is why we define it
here but enable it globally.
#+BEGIN_SRC emacs-lisp
  (use-package flycheck
    :init (global-flycheck-mode))
#+END_SRC

* Magit
git porcelain
#+BEGIN_SRC emacs-lisp
  (use-package magit
    :bind ("C-c g" . magit-status))
#+END_SRC

* Treemacs
A tree renderer of your directory. Useful for seeing files in your
project and includes integration with magit.
#+BEGIN_SRC emacs-lisp
  (use-package treemacs
    :defer t
    :bind (("C-c t b"   . treemacs-select-window)
           ("C-c t 1"   . treemacs-delete-other-windows)
           ("C-c t B"   . treemacs-bookmark)
           ("C-c t C-t" . treemacs-find-file)
           ("C-c t M-t" . treemacs-find-tag))
           ("C-c t d"   . treemacs-select-directory)
           ("C-c t t"   . treemacs))

  (use-package treemacs-magit
    :after (treemacs magit))

  (use-package treemacs-tab-bar ;;treemacs-tab-bar if you use tab-bar-mode
    :after (treemacs)
    :config (treemacs-set-scope-type 'Tabs))
#+END_SRC
* Whitespace
Colorize whitespace characters for prog mode.
#+BEGIN_SRC emacs-lisp
  (use-package whitespace
    :config
    (setq whitespace-line-column 120)
    (setq whitespace-style '(face lines-tail))
    :hook (prog-mode . whitespace-mode))
#+END_SRC

* WS-butler
Removes trailing space and tabs from this user modified lines.
#+BEGIN_SRC emacs-lisp
  (use-package ws-butler
    :hook ((prog-mode . ws-butler-mode)
           (org-mode . ws-butler-mode)
           (text-mode . ws-butler-mode)))
#+END_SRC

* Yasnippet
Enables snippets for progamming and text modes.
#+BEGIN_SRC emacs-lisp
  (use-package yasnippet
    :config
    (yas-reload-all)
    :hook ((prog-mode . yas-minor-mode)
           (text-mode .  yas-minor-mode)))
#+END_SRC
