#+TITLE: Progamming Settings
#+STARTUP: OVERVIEW
* Introduction
Programming related settings and packages defined here. Language
Server Protocol (LSP) provides IDE-like features and is configured
here. Some relevant minor modes also set here, including their look
and feel if appropriate. But first... let's get rid of tabs!
#+BEGIN_SRC emacs-lisp
  (setq-default indent-tabs-mode nil)
#+END_SRC

* Programming Languages Modes
** Rust
Rust-specific settings and packages. First remap the default major
mode with Treesitter variant.
#+BEGIN_SRC emacs-lisp
  (use-package rust-ts-mode
    :config
    (add-to-list 'major-mode-remap-alist '(rust-mode . rust-ts-mode)))
#+END_SRC

The `rustic` package enriches Emacs for editing rust source code.
However, at the time of writing `rustic` is incompatible with
`rust-ts-mode`. But seeing as we would like to retain the compilation
convenience functions, we still install the package and use its
bindings in `rust-ts-mode`.
#+BEGIN_SRC emacs-lisp
  (use-package rustic
    :config
    (setq rustic-format-on-save nil
          rustic-lsp-client nil)
    :bind (:map rust-ts-mode-map
                ("C-c C-c C-c" . rustic-recompile)
                ("C-c C-c C-r" . rustic-cargo-run)
                ("C-c C-c C-l" . rustic-cargo-clippy-run)
                ("C-c C-c C-f" . rustic-cargo-clippy-fix)
                ("C-c C-c C-r" . rustic-cargo-run)
                ("C-c C-c C-t" . rustic-cargo-test)))
  #+END_SRC

** Python
Python-specific settings and packages. Since Emacs 29 we have Python
with Treesitter support.
#+BEGIN_SRC emacs-lisp
  (setq python-ts-mode-hook python-mode-hook)
  (add-to-list 'major-mode-remap-alist '(python-mode . python-ts-mode))
#+END_SRC

*** auto-virtualenv
Automatically activate Python virtual environments with `auto-virtualenv`.
#+BEGIN_SRC emacs-lisp
  (use-package auto-virtualenv
    :defer t
    :config
    (advice-add #'project-switch-to-buffer :after #'auto-virtualenv-set-virtualenv)
    :hook (python-ts-mode . auto-virtualenv-set-virtualenv))
#+END_SRC

*** black
#+BEGIN_SRC emacs-lisp
  (use-package python-black
    :defer t
    :hook (python-ts-mode . python-black-on-save-mode-enable-dwim))
#+END_SRC

*** pyenv
Use `pyvenv` to manage Python virtual environments.
#+BEGIN_SRC emacs-lisp
  (use-package pyvenv :defer t)
#+END_SRC

* Language Server Protocol
Setup Language Server Protocol (LSP) for different programming
languages. We use eglot which is built-in >= Emacs 29.
#+BEGIN_SRC emacs-lisp
  (use-package eglot
    :defer t
    :bind (:map eglot-mode-map
                ("C-c e r" . eglot-rename)
                ("C-c e f" . eglot-format)
                ("C-c e d" . eglot-find-declaration)
                ("C-c e i" . eglot-find-implementation))
    :config
    (set-face-attribute 'eglot-highlight-symbol-face nil
                        :inherit 'match)
    :hook ((rust-ts-mode python-ts-mode haskell-ts-mode) . eglot-ensure))

  (use-package eldoc-box
    :after eglot
    :defer t
    :config
    (set-face-attribute 'eldoc-box-body nil
                        :inherit 'default))
#+END_SRC

* Modes
Many of these mode are activated by adding a hook to `prog-mode-hook`
or is highly associated with programming.
** ediff
Ediff is used for viewing diffs and acting upon them. We want the
control that normally displays in another frame to be place in the
same window.
#+BEGIN_SRC emacs-lisp
  (setq ediff-window-setup-function 'ediff-setup-windows-plain)
#+END_SRC

** electric mode
Automatically add closing brackets and indent code in `prog-mode`.
#+BEGIN_SRC emacs-lisp
  (defun hesam/electric ()
    (electric-pair-local-mode t)
    (electric-indent-local-mode t))
  (add-hook 'prog-mode-hook #'hesam/electric)
#+END_SRC

** hideshow
Set up the `hideshow` minor mode for `prog-mode`.
#+BEGIN_SRC emacs-lisp
  (setq hs-allow-nesting t)
  (add-hook 'prog-mode-hook 'hs-minor-mode)
  (eval-after-load 'prog-mode
    '(define-key prog-mode-map (kbd "C-<return>") 'hs-toggle-hiding))
#+END_SRC

Another symbol to be used for collapsed text.
#+BEGIN_SRC emacs-lisp
  (set-display-table-slot standard-display-table
                          'selective-display (string-to-vector " [+] "))
#+END_SRC

** row/column/line numbers
Shows column number in `mode-line` in addtion to row number.
#+BEGIN_SRC emacs-lisp
  (add-hook 'prog-mode-hook 'column-number-mode)
#+END_SRC

** Show parent
Highlights matching parens in prog-mode.
#+BEGIN_SRC emacs-lisp
  (add-hook 'prog-mode-hook 'show-paren-mode)
#+END_SRC

* git
** git-timemachine
In a git-tracked repository we can invoke `git-timemachine` to quickly
navigate between revisions, show commits and use git blame. When
visiting a git tracked file and calling `git-timemachine`
interatively, it allows us to move between revisions with `n`,
`p`. Hit `?` to get a hydra-like menu for more commands.
#+BEGIN_SRC emacs-lisp
  (use-package git-timemachine
    :defer t
    :after magit)
#+END_SRC

** Magit
git porcelain
#+BEGIN_SRC emacs-lisp
  (use-package magit
    :demand t
    :after project
    :bind ("C-c g" . magit-status)
    :config
    (advice-add #'project-vc-dir :override #'magit-project-status))
#+END_SRC

* Flymake
Flymake is an built-in syntax checker for Emacs to be used everywhere,
but it's stronlgy linked to programming and that is why we define it
here.

Out of intereset here is the setting `flymake-no-changes-timeout`. If
set to a number, then Flymake will check the file after waiting that
number in seconds for each change you make in the buffer.
#+BEGIN_SRC emacs-lisp
  (use-package flymake
    :config
    (setq flymake-no-changes-timeout 0.5
          flymake-proc-compilation-prevents-syntax-check t
          flymake-start-on-flymake-mode t
          flymake-start-on-save-buffer t
          flymake-suppress-zero-counters t
          flymake-wrap-around nil
          flymake-fringe-indicator-position 'left-fringe))
#+END_SRC

* NeoTree
A tree renderer of your filesystem. Useful for seeing files in your
project and to preform basic operations on them, such as renaming and
copying.
#+BEGIN_SRC emacs-lisp
  (use-package neotree
    :defer t
    :config
    (setq neo-theme 'arrow
          neo-smart-open t)
    :bind (("C-c n d" . neotree-dir)
           ("C-c n t" . neotree-toggle)))
#+END_SRC

* Treesit-auto
#+BEGIN_SRC emacs-lisp
  (use-package treesit-auto
    :demand t
    :config
    (setq treesit-auto-install t)
    (global-treesit-auto-mode))
#+END_SRC

* vundo
In this excellet [[https://archive.casouri.cc/note/2021/visual-undo-tree/index.html][blog]] Yuan Fu describes a way of creating an undo-tree
from Emacs' linear tree. This enables us to build an undo-tree on the
fly, navigate it and make Emacs go to that state. Born is the package
`vundo` (visualize undo).
#+BEGIN_SRC emacs-lisp
  (use-package vundo :defer t)
#+END_SRC

* ws-butler
Removes trailing space and tabs from this user modified lines.
#+BEGIN_SRC emacs-lisp
  (use-package ws-butler
    :defer t
    :hook ((prog-mode text-mode) . ws-butler-mode))
#+END_SRC

